services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  apigw:
    build: ./apigw
    ports:
      - "4000:4000"
    depends_on:
      - productservice
      - userservice
    environment:
      - PRODUCT_SERVICE_URL=http://productservice:4001
      - USER_SERVICE_URL=http://userservice:4002

  productservice:
    build: ./productservice
    ports:
      - "4001:4001"

  userservice:
    build: ./userservice
    ports:
      - "4002:4002"

  kafkaservice:
    build: ./kafkaservice
    ports:
      - "5004:5004" # Optional, only if kafkaservice exposes HTTP
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
# RabbitMQ Service for interacting with RabbitMQ
  rabbitmqservice:
    build: ./rabbitmqservice
    ports:
      - "5005:5005"  # Optional, only if rabbitmqservice exposes HTTP
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672

volumes:
  rabbitmq_data: {} # Used for RabbitMQ data persistence